version: '3.9'
services:
  postgresql:
    image: postgres:15-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  data:
